# Site
name: "NinggraIngga"
title: "NinggraIngga"
description: "Discover the world's Hidden Vacation Gems"
logo: '/favicon.ico'
favicon: '/favicon.ico'
baseurl: /
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  admin:
    name: Sri Maulina Rahayu
    display_name: Sri Maulina Rahayu
    gravatar: https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj2AaXiYUE5PUuANF4ocuJxOgzmC_vzz8HPlqfKiUuwCHxEZ-N1OJZo4S-7MjNjcTcO7Eb9gX-8rnDI7-BFfkHkm1coVmimfTYqWwAibnTxW1ywbzI9K0WPvs-RoCxNBslGq164qldUifOdsfAyQtFQoxH0S4cGYrAjnn0zeyaaiOPlJbtXJlqBIvXcHvFC/s1600/20240923_190539.jpg
    email: ninggraingga@gmail.com
    web: /aboutme
    description: "Writing is the art of giving voice to the silent thoughts transforming the invisible into something the world can feel and understand."
  admin2:
    name: indriani tresna asih
    display_name: indriani tresna asih   
    gravatar: https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh9AZTJwjgfei91oCQOiKvu17a7yxxxL_oxmWm0JNRoqK2rpUtCV8s2OqBTZ9_dwWV4qlm2FWZlXjO1AkwrtDDgNc_jKQO7q5zrnsvY7r3eBhPiLp51xVEbuWMifzKV9iFJM1wCtwg2DK2d2FFps0wv7ZF0zOoZCSXetCe-VR64_wIZ-x0z8f5HoI1LkwJQ/s1600/20240926_205418.jpg
    email: wowthemesnet@gmail.com
    web: /aboutme2
    description: "Every word we write is a small step toward immortality leaving behind a lasting imprint that transcends the limitations of time."
  admin3:
    name: rais fazriansyah
    display_name: rais fazriansyah   
    gravatar: https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgQzgvewbmJ9t-MZdbl_LimOMVaWtTNW3_HhpZemtdxC7K34ey46PDnN8HjH2pHK2j4obd7e-pqZtLEZ1pmr796xh-P9kX00gNrc9_RStwlUa9v9XJQzTC2iw1pjpl6rkh9R8YmP6JElswOEbiC82ea2wtrVXPviUFCxLRorLKQ7VrNE4cvvKX3Ogrz3jM/s1600/20241001_073006.jpg
    email: r.fazriansyah@gmail.com
    web: /aboutme3
    description: "The power of the pen is not just in the act of expression but in its ability to ignite change stir emotions and inspire minds."
  admin4:
    name: Ghea Melinda
    display_name: Ghea Melinda   
    gravatar: https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjuFpsLztF25khx0Y5areM6r7m0Z-My65sjZB4aD1gJYLfQFPR9YsWwP_Bl8yLnRR0R6TXWPI6_rWhhXygx5FfteQdomj7RGUe4P1uo9UeazJWmS27eZMfU_sOW180Suwfnu3dwxTllLw1hA3a3hH9YmHbyo7anykR41FjcjWGVRa5mxpLEWjl5o-cqaKs/s1600/20241001_121304.jpg
    email: gheamelinda26@gmail.com
    web: /aboutme4
    description: "Writing opens windows to the depths of the soul, revealing layers of truth and emotion that often go unnoticed in everyday life."
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 4
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
